name: Screenshot

on:
  push:
    branches:
      - main
    paths:
      - "solutions/**"
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: install dependencies
        run: bun install

      - name: run screenshot script
        run: bun run main.ts

      - name: commit screenshot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add screenshot/score.png
          git commit -m "update score screenshot"
          git push
